"""remove_index_order_user_migration_002

Revision ID: b45e46c70017
Revises: 196a570ce6f4
Create Date: 2025-08-09 15:22:32.214445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45e46c70017'
down_revision: Union[str, Sequence[str], None] = '196a570ce6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user'), table_name='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_user'), 'orders', ['user'], unique=False)
    # ### end Alembic commands ###
